-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
CPF VARCHAR(10) PRIMARY KEY,
NOME VARCHAR(10)
)

CREATE TABLE DESTINOS (
LOCALIZAÇÃO VARCHAR(10),
ID LOCALIZAÇÃO VARCHAR(10) PRIMARY KEY
)

CREATE TABLE PLANOS (
PREÇO VARCHAR(10),
ID PLANOS VARCHAR(10) PRIMARY KEY,
NOME VARCHAR(10)
)

CREATE TABLE compra (
ID PLANOS VARCHAR(10),
CPF VARCHAR(10),
FOREIGN KEY(ID PLANOS) REFERENCES PLANOS (ID PLANOS),
FOREIGN KEY(CPF) REFERENCES CLIENTE (CPF)
)

CREATE TABLE pertence (
ID LOCALIZAÇÃO VARCHAR(10),
ID PLANOS VARCHAR(10),
FOREIGN KEY(ID LOCALIZAÇÃO) REFERENCES DESTINOS (ID LOCALIZAÇÃO),
FOREIGN KEY(ID PLANOS) REFERENCES PLANOS (ID PLANOS)
)

